# <file>
# <summary>
# Mass-spring primitives and force helpers.
# </summary>
# </file>
"""Mass-spring primitives and force helpers."""

from __future__ import annotations

from dataclasses import dataclass
from math import hypot
from typing import Iterable

from .math2d import Vec2
from .particle import Particle


# <summary>
# Connects two particles in a spring network.
# </summary>
@dataclass(slots=True)
class Spring:
    """Connects two particles in a spring network."""

    particle_a: Particle
    particle_b: Particle
    rest_length: float
    stiffness: float
    damping: float

    # <summary>
    # Create a spring between two particles, deriving rest length when omitted.
    # </summary>
    # <param name="particle_a">Input value for particle a.</param>
    # <param name="particle_b">Input value for particle b.</param>
    # <param name="stiffness">Input value for stiffness.</param>
    # <param name="damping">Input value for damping.</param>
    # <param name="rest_length">Input value for rest length.</param>
    # <returns>Computed result described by the return type annotation.</returns>
    @classmethod
    def between(
        cls,
        particle_a: Particle,
        particle_b: Particle,
        stiffness: float,
        damping: float = 0.0,
        rest_length: float | None = None,
    ) -> "Spring":
        if rest_length is None:
            dx = particle_b.position.x - particle_a.position.x
            dy = particle_b.position.y - particle_a.position.y
            natural_length = hypot(dx, dy)
        else:
            natural_length = rest_length
        return cls(particle_a, particle_b, natural_length, stiffness, damping)

    # <summary>
    # Return the current endpoint distance.
    # </summary>
    # <returns>Computed result described by the return type annotation.</returns>
    def length(self) -> float:
        dx = self.particle_b.position.x - self.particle_a.position.x
        dy = self.particle_b.position.y - self.particle_a.position.y
        return hypot(dx, dy)

    # <summary>
    # Calculate the force pair generated by this spring.
    # </summary>
    # <returns>Computed result described by the return type annotation.</returns>
    def force(self) -> tuple[Vec2, Vec2]:
        return spring_force(
            a_position=self.particle_a.position,
            a_velocity=self.particle_a.velocity,
            b_position=self.particle_b.position,
            b_velocity=self.particle_b.velocity,
            rest_length=self.rest_length,
            stiffness=self.stiffness,
            damping=self.damping,
        )

    # <summary>
    # Return a unit normal perpendicular to the spring segment.
    # </summary>
    # <returns>Computed result described by the return type annotation.</returns>
    def normal(self) -> Vec2:
        dx = self.particle_b.position.x - self.particle_a.position.x
        dy = self.particle_b.position.y - self.particle_a.position.y
        distance = hypot(dx, dy)
        if distance == 0.0:
            return Vec2()
        inverse_distance = 1.0 / distance
        return Vec2(dy * inverse_distance, -dx * inverse_distance)

    # <summary>
    # Accumulate the spring's equal and opposite forces on its particles.
    # </summary>
    def apply(self) -> None:
        particle_a = self.particle_a
        particle_b = self.particle_b
        dx = particle_b.position.x - particle_a.position.x
        dy = particle_b.position.y - particle_a.position.y
        distance_sq = dx * dx + dy * dy
        if distance_sq == 0.0:
            return

        distance = hypot(dx, dy)
        inverse_distance = 1.0 / distance
        normal_x = dx * inverse_distance
        normal_y = dy * inverse_distance

        relative_velocity_x = particle_b.velocity.x - particle_a.velocity.x
        relative_velocity_y = particle_b.velocity.y - particle_a.velocity.y
        spring_term = self.stiffness * (distance - self.rest_length)
        damping_term = self.damping * (
            relative_velocity_x * normal_x + relative_velocity_y * normal_y
        )
        force_x = normal_x * (spring_term + damping_term)
        force_y = normal_y * (spring_term + damping_term)

        particle_a.force.x += force_x
        particle_a.force.y += force_y
        particle_b.force.x -= force_x
        particle_b.force.y -= force_y


# <summary>
# Apply spring forces with a flat loop to reduce Python call overhead.
# </summary>
# <param name="springs">Spring collection being read or updated.</param>
def apply_springs(springs: Iterable[Spring]) -> None:
    """Apply spring forces with a flat loop to reduce Python call overhead."""

    for spring in springs:
        spring.apply()


# <summary>
# Return equal and opposite spring forces for two endpoints.
# </summary>
# <param name="a_position">Input value for a position.</param>
# <param name="a_velocity">Input value for a velocity.</param>
# <param name="b_position">Input value for b position.</param>
# <param name="b_velocity">Input value for b velocity.</param>
# <param name="rest_length">Input value for rest length.</param>
# <param name="stiffness">Input value for stiffness.</param>
# <param name="damping">Input value for damping.</param>
# <returns>Computed result described by the return type annotation.</returns>
def spring_force(
    a_position: Vec2,
    a_velocity: Vec2,
    b_position: Vec2,
    b_velocity: Vec2,
    rest_length: float,
    stiffness: float,
    damping: float,
) -> tuple[Vec2, Vec2]:
    """Return equal and opposite spring forces for two endpoints."""

    delta = b_position - a_position
    distance = delta.length()
    if distance == 0.0:
        return Vec2(), Vec2()

    direction = delta / distance
    relative_velocity = b_velocity - a_velocity
    spring_term = stiffness * (distance - rest_length)
    damping_term = damping * relative_velocity.dot(direction)
    force_on_a = direction * (spring_term + damping_term)
    return force_on_a, -force_on_a
